name: Build and Release

on:
  push:
    branches: [ "feat-dockerize" ]

jobs:

  increment-version-tag:
    name: increment the patch number in version tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine next patch version
      id: version
      run: |
        git fetch --tags

        # obtain latest version tag 
        LATEST_TAG=$(git tag --list 'v*.*.*' --sort=-v:refname | head -n 1)

        if [[ -z "$LATEST_TAG" ]]; then
          MAJOR=0
          MINOR=1
          PATCH=0
        else
          MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | cut -dv -f2)
          MINOR=$(echo $LATEST_TAG | cut -d. -f2)
          PATCH=$(echo $LATEST_TAG | cut -d. -f3)
          PATCH=$((PATCH + 1))
        fi

        NEW_TAG="v$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_TAG"
        echo "version=$NEW_TAG" >> $GITHUB_OUTPUT

  build-binaries:
    needs: increment-version-tag
    name: Build and Release for All Platforms
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ needs.increment-version-tag.outputs.version }}" -o dist/AutoTickets-Linux 
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=${{ needs.increment-version-tag.outputs.version }}" -o dist/AutoTickets.exe
    - name: Build for macOS (intel)
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ needs.increment-version-tag.outputs.version }}" -o dist/AutoTickets-Mac-Intel
    - name: Build for macOS (arm)
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ needs.increment-version-tag.outputs.version }}" -o dist/AutoTickets-Mac-Arm
   
    - name: upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  github-release:
    needs: [build-binaries, increment-version-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.increment-version-tag.outputs.version }}
          name: Release ${{ needs.increment-version-tag.outputs.version }}
          files: |
            dist/AutoTickets-Linux
            dist/AutoTickets.exe
            dist/AutoTickets-Mac-Arm
            dist/AutoTickets-Mac-Intel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push new tag to Git
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git tag ${{ needs.increment-version-tag.outputs.version }}
          git push origin ${{ needs.increment-version-tag.outputs.version }}

  build-and-publish-image:
    needs: [build-binaries, increment-version-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Lowercase repository name
        id: repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: build and publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.name }}:${{ needs.increment-version-tag.outputs.version }}
            ghcr.io/${{ steps.repo.outputs.name }}:latest
            ${{ steps.ecr-login.outputs.registry }}/autotickets:${{ needs.increment-version-tag.outputs.version }}
            ${{ steps.ecr-login.outputs.registry }}/autotickets:latest

